### ISSUE TITLE
Developer Portal and Developer Academy Linking to Incorrect IBC Website

### ISSUE THREAD

**Issue by zadkiel88** [cosmos/developer-portal#72]
We are performing a backlinks audit of the IBC website, and discovered the Developer Portal and Developer Academy have various links that direct to the old IBC website. They need to be updated to direct to the new IBC website. 

I am opening this issue at Syed's request in order to add these updates to the development workflow.

The outdated URLs and correct target URLs for both properties can be found in tab 1 and tab 2 of this Google Sheet:

https://docs.google.com/spreadsheets/d/1mV7pXxNQkZcECygaF3pOkR7ZurqVZWb5dVEnjhu7qm0/edit?usp=sharing

**Comment by coldice** [comment]
Fixed in #73 and on the Landingpage (https://git.b9lab.com/client-projects/cosmos/academy-website/web-ca-main-project/-/tree/dist **internal link**)
